/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.game;

public class App {
  public static void main(String[] args) {
    System.out.println("[게임 애플리케이션]");
    System.out.println();
    System.out.println("환영합니다!!");
    System.out.println();

    java.util.Scanner keyboardInput = new java.util.Scanner(System.in);

    while (true) {
      System.out.println("선택지:");
      System.out.println("  1: 가위");
      System.out.println("  2: 바위");
      System.out.println("  3: 보");
      System.out.println();
      System.out.print("선택하세요[1..3](0: 종료)");

      int menuNo = keyboardInput.nextInt();
      keyboardInput.nextLine();
      if (menuNo == 0) {
        break;
      } else if (menuNo == 1) {
        System.out.println("당신은 이겼습니다.");
        break;
      } else if (menuNo == 2) {
        System.out.println("당신은 졌습니다.");
        break;
      } else if (menuNo == 3) {
        System.out.println("당신은 비겼습니다");
        break;
      } else {
        System.out.println("번호가 옳지 않습니다.");
      }
    } // while
    System.out.println("게임종료");
    keyboardInput.close();
  }
}
